[versions]
concurrent = "1.3.0"
core = "1.12.0"
lifecycle = "2.9.4"
navigation = "2.9.6"
room = "2.6.1"

[libraries]
activity = "androidx.activity:activity:1.10.1"
annotation = "androidx.annotation:annotation:1.9.1"
appCompat = "androidx.appcompat:appcompat:1.7.1"
concurrent-futures-core = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent" }
concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent" }
constraintLayout = "androidx.constraintlayout:constraintlayout:2.2.1"
coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:1.3.0"
core = { module = "androidx.core:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
core-testing = "androidx.arch.core:core-testing:2.2.0"
documentFile = "androidx.documentfile:documentfile:1.1.0"
lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
recyclerView = "androidx.recyclerview:recyclerview:1.4.0"
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
startup = "androidx.startup:startup-runtime:1.1.1"
swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

[bundles]
lifecycle = ["lifecycle-liveData", "lifecycle-viewModel"]
navigation = ["navigation-fragment", "navigation-ui"]

[plugins]
room = "androidx.room:2.8.4"